# Generated by Django 2.1.5 on 2019-01-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='state')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, verbose_name='username')),
                ('phone_no', models.CharField(max_length=60, verbose_name='phone_no')),
                ('email_id', models.CharField(max_length=128, verbose_name='email_id')),
                ('location', models.CharField(max_length=60, verbose_name='location')),
                ('feedback', models.TextField(max_length=500, verbose_name='feedback')),
            ],
        ),
    ]
